# Generated by Django 3.2.16 on 2022-12-08 11:01

from django.db import migrations
import wagtail.blocks
import wagtail.documents.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0003_merge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivepage',
            name='body',
            field=wagtail.fields.StreamField([('archive_list', wagtail.blocks.StructBlock([('archives', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock()), ('text', wagtail.blocks.TextBlock()), ('time', wagtail.blocks.CharBlock()), ('link', wagtail.blocks.StructBlock([('url', wagtail.blocks.URLBlock()), ('label', wagtail.blocks.CharBlock())])), ('documents', wagtail.blocks.ListBlock(wagtail.documents.blocks.DocumentChooserBlock()))])))]))], use_json_field=True),
        ),
    ]
