language: python
dist: bionic
python:
- '3.6'
cache:
  pip: true
  npm: true
install:
- nvm install 8
- npm install
- npm run build
- pip install -r requirements/dev.txt
script:
- python manage.py makemigrations --dry-run --check --noinput
- isort --diff -rc -c apps tempelhof
- flake8 apps tempelhof --exclude migrations,settings
- npm run lint
deploy:
- provider: script
  script: scripts/deploy.sh
  on:
    branch: master
env:
  global:
    secure: oQq/qN+JIRzttdTnBMzWucLtn2INPC02ukFVXMyoQSgvbdwCCcJy5tlfzi6xE6FSOkvLzPZxK/vDd/wVmQFjlrcYJV9l58cQugo0JKtDIUKWO1Gq8WoK81Jr/MIQGK/gGBaMnT9Uy0nAEMCCTCgVitIfswOFzZVs5K98FE5rWcBto0FE7JtdVYRVhRdMVGas5udW/bvS65UFQbTotIxCSn3khUDBO93c9y92KOqPvSKXbER2bm+8CqMjhgWYVeTKRkWqi0ibVNIDfFE/w/EjquJjmMns8yjGdr3GSQ4aPDQcbiBqVKlAMZhzUXCYaDoNV+8dU9+Ur3pqjFgmrRQzYZnMR4+ctXuVXsgecIxuENAC3mZFUeeEoQzYAXOmD4E32khK7H4rKxq5AzihC2FXFglgLl9zzg9ocG1vwsu6k+QbKaJnSauH+pVtIcKKYfav/TTRLlx0FaFJEMcpL/aclr3QrgHmcmfiz2wPrZmsTCjOn+JYzEkHkI8DZuH+RRye0VO35fRq8JwasdyYEPzLo7Ax9Yx5vpdez+KKgUOqdC4PUSYA2nlPvi+YPOu6za9fS2HeYpBzDrW24umD6YAl2QDaa5qlpEtpssAWOUS/uiWexK9fcuLrS5iNE/ACjqCjnRzzlF5ecPAVUU6x+NW5Ljo5S7TZWqo+bnKzJzpO8aY=
