# Generated by Django 3.2.16 on 2022-12-08 11:01

from django.db import migrations
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0005_use-rte-instead-of-separate-field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docspage',
            name='body',
            field=wagtail.fields.StreamField([('documents_list', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock()), ('images', wagtail.blocks.ListBlock(wagtail.images.blocks.ImageChooserBlock())), ('body', wagtail.blocks.RichTextBlock(required=False))]))], use_json_field=True),
        ),
    ]
