# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-29 14:13
from __future__ import unicode_literals

import apps.home.blocks
import apps.projects.blocks
from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_add_calendar_link_to_calendar_block'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='body',
            field=wagtail.fields.StreamField((('text', wagtail.blocks.RichTextBlock(icon='doc-full', template='home/blocks/text.html')), ('teasers', wagtail.blocks.StructBlock((('teasers', wagtail.blocks.ListBlock(apps.home.blocks.TeaserBlock)),))), ('columns', wagtail.blocks.StructBlock((('columns', wagtail.blocks.ListBlock(apps.home.blocks.ColumnBlock)),))), ('projects', wagtail.blocks.StructBlock((('title', wagtail.blocks.CharBlock()), ('projects', wagtail.blocks.ListBlock(apps.projects.blocks.CurrentProjectBlock))))), ('updates', wagtail.blocks.StructBlock((('status', wagtail.blocks.PageChooserBlock(target_model=['blog.BlogEntryPage'])), ('calendar', wagtail.blocks.StructBlock((('calendar_link_text', wagtail.blocks.CharBlock(required=False)), ('calendar_link', wagtail.blocks.PageChooserBlock(required=False, target_model=['events.CalendarPage'])))))))))),
        ),
    ]
